apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: todo-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api-app
      tier: app
  template:
    metadata:
      name: todo-api
      labels:
        app: todo-api-app
        tier: app
    spec:
      containers:
        - name: todo-api
          image: sajalshres/todo-on-rails:latest
          imagePullPolicy: Always
          args: ["rails", "s", "-b", "0.0.0.0"]
          env:
            - name: API_DATABASE_PASSWORD
              value: dbpassword@2020
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
