apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: todo-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api-app
      tier: database
  template:
    metadata:
      name: postgres
      labels:
        app: todo-api-app
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:12
          env:
            - name: POSTGRES_DB
              value: todo_db
            - name: POSTGRES_USER
              value: dbuser
            - name: POSTGRES_PASSWORD
              value: dbpassword@2020
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
